server:
  port: ${WAS_PORT}

spring:
  config:
    import: "optional:file:./.env.dev[.properties]"
  autoconfigure:
    exclude: []
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: blog
  flyway:
    enabled: true
    default-schema: blog
    schemas: blog
    baseline-on-migrate: true

app:
  visitor:
    cookie-secure: false
    trusted-proxies: ${VISITOR_TRUSTED_PROXIES:}
